name: Basic tests

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: False
      matrix:
        command:
          - pytest --runslow
          # TODO This should cover more than just tests/CI
          # Excluded codes related to sourcing files
          #     SC1090: Can't follow non-constant source
          #     SC1091: Not following sourced file
          - find tests/CI -name '*.sh' -print0 | xargs -0 -n1 shellcheck --exclude=SC1090,SC1091 --external-source
          - tests/runPylint.sh
          - tests/py3Check.sh
          - CHECK=pylintPY3K tests/runPylint.sh
          - |
            if [[ "${REFERENCE_BRANCH}" != "" ]]; then
                git remote add upstream https://github.com/DIRACGrid/DIRAC.git
                git fetch --no-tags upstream "${REFERENCE_BRANCH}"
                git branch -vv
                git diff -U0 "upstream/${REFERENCE_BRANCH}" ':(exclude)tests/formatting/pep8_bad.py' | pycodestyle --diff
            fi

    steps:
    - uses: actions/checkout@v2
    - name: Fail-fast for outdated pipelines
      run: .github/workflows/fail-fast.sh
    - name: Prepare environment
      run: |
        conda env create --name dirac-testing environment.yml
    - name: Run tests
      run: |
        source "${CONDA}/bin/activate"
        conda activate dirac-testing
        set -euxo pipefail
        export PYTHONPATH=${PWD}/src
        ${{ matrix.command }}
      env:
        REFERENCE_BRANCH: ${{ github['base_ref'] || github['head_ref'] }}
