name: Integration tests

on: [push, pull_request]

jobs:
  Integration:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: False
      matrix:
        # TEST_NAME is a dummy variable used to make it easier to read the web interface
        include:
          ###### MySQL versions
          - TEST_NAME: "MySQL 5.7"
            ARGS: MYSQL_VER=5.7
          # ###### ES versions
          - TEST_NAME: "Elasticsearch 6.6.0"
            ARGS: ES_VER=6.6.0
          ###### Thread pool
          - TEST_NAME: "New thread pool"
            ARGS: DIRAC_USE_NEWTHREADPOOL=No
          ###### Thread pool
          - TEST_NAME: "Fewer cfg locks"
            ARGS: DIRAC_FEWER_CFG_LOCKS=Yes
          ###### HTTPS tests
          - TEST_NAME: "HTTPS"
            ARGS: TEST_HTTPS=Yes
          ###### Python 3
          - TEST_NAME: "Python 3 client"
            ARGS: CLIENT_USE_PYTHON3=Yes
          - TEST_NAME: "Python 3 server"
            ARGS: SERVER_USE_PYTHON3=Yes
          - TEST_NAME: "Python 3 server and client"
            ARGS: CLIENT_USE_PYTHON3=Yes SERVER_USE_PYTHON3=Yes MYSQL_VER=8.0

    steps:
    - uses: actions/checkout@v2
    - name: Fail-fast for outdated pipelines
      run: .github/workflows/fail-fast.sh
    - run: |
        git fetch --prune --unshallow
    - uses: conda-incubator/setup-miniconda@master
      with:
        environment-file: environment-py3.yml
        miniforge-variant: Mambaforge
        use-mamba: true
    - name: Prepare environment
      run: ./integration_tests.py prepare-environment ${{ matrix.ARGS }}
    - name: Install server
      run: ./integration_tests.py install-server
    - name: Install client
      run: ./integration_tests.py install-client
    - name: Server tests
      run: ./integration_tests.py test-server || touch server-tests-failed
    - name: Client tests
      run: ./integration_tests.py test-client || touch client-tests-failed
    - name: Elasticsearch logs
      run: docker logs elasticsearch
    - name: Check test status
      run: |
        has_error=0
        if [ -f server-tests-failed ]; then has_error=1; echo "Server tests failed"; fi
        if [ -f client-tests-failed ]; then has_error=1; echo "Client tests failed"; fi
        if [ ${has_error} = 1 ]; then exit 1; fi
